name: WitchPotions
main: com.craftilandia.witchpotions.Main
version: 9.0
author: raton023
website: http://dev.bukkit.org/bukkit-plugins/witchpotions/
permissions:
    witchpotions.create:
        description: to create potions.
        default: true
